version: 2
root-markers:
  - .git/
lint-debounce: 0.5s

tools:
  mix_credo: &mix_credo
    lint-command: "MIX_ENV=test mix credo suggest --format=flycheck --read-from-stdin ${INPUT}"
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %t: %m'
      - '%f:%l: %t: %m'
    root-markers:
      - mix.lock
      - mix.exs
  mix_format: &mix_format
    format-command: 'mix format - ${INPUT}'
    format-stdin: true
  eslint: &eslint
    lint-command: 'eslint_d -f unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
  prettier: &prettier
    format-command: 'prettierd ${INPUT}'
    format-stdin: true
  luaformat: &luaformat
    format-command: "lua-format -i --no-keep-simple-function-one-line --no-break-after-operator --column-limit=150 --break-after-table-lb"
    format-stdin: true

languages:
  elixir:
    - <<: *mix_credo
    - <<: *mix_format
  javascript:
    - <<: *eslint
    - <<: *prettier
  typescript:
    - <<: *eslint
    - <<: *prettier
  javascriptreact:
    - <<: *eslint
    - <<: *prettier
  typescriptreact:
    - <<: *eslint
    - <<: *prettier
  yaml:
    - <<: *prettier
  json:
    - <<: *prettier
  html:
    - <<: *prettier
  scss:
    - <<: *prettier
  css:
    - <<: *prettier
  markdown:
    - <<: *prettier
  lua:
    - <<: *luaformat

